// app/layout.tsx
import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Providers } from "@/components/providers/providers"; // Merkezi provider'ımızı import ediyoruz

export const metadata: Metadata = {
  title: "Orcish Dashboard",
  description: "Generated by Çağatay Ersoy with Gemini",
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#09090b" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr" suppressHydrationWarning>
      <body>
        {/* Artık sadece tek bir Providers bileşeni çağırıyoruz */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
